Added to docker

diff --git a/project/docker-compose.yml b/project/docker-compose.yml
--- a/project/docker-compose.yml
+++ b/project/docker-compose.yml
@@ -14,6 +14,7 @@ services:
         condition: service_healthy
     networks:
       - events-network
+      - state-service
 #      GIN_MODE: "release"
   profile-monitor:
     build:
@@ -33,6 +34,23 @@ services:
     networks:
       - profile-service
       - profile-manager
+      - state-service
+
+  state-service:
+    build:
+      context: ${PWD}/../StateService
+      dockerfile: ${PWD}/../StateService/Dockerfile
+    restart: always
+    ports:
+      - "8086:80"
+    environment:
+      APP_ENV: docker
+      APP_CONF_PATH: "/app/"
+    depends_on:
+      - profile-monitor
+      - redis
+    networks:
+      - state-service
 
   package-service:
     build:
@@ -82,6 +100,7 @@ services:
       - profile-manager
     networks:
       - profile-manager
+      - state-service
 
   redis:
     image: redis:latest
@@ -101,7 +120,7 @@ services:
       timeout: 10s
       retries: 5
     networks:
-      - eventCollector
+      - state-service
 
   postgres:
     image: postgres:latest
@@ -198,88 +217,88 @@ services:
     deploy:
       replicas: ${KAFKA_REPLICAS:-1}  # Default to 0, meaning Kafka won't start unless KAFKA_REPLICAS is set
 
-  pinot-controller:
-    image: ${PINOT_IMAGE:-apachepinot/pinot:1.2.0}
-    command: "StartController -zkAddress pinot-zookeeper:2181"
-    container_name: "pinot-controller"
-    restart: unless-stopped
-    ports:
-      - "9000:9000"
-    environment:
-      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-controller.log"
-    depends_on:
-      pinot-zookeeper:
-        condition: service_healthy
-    networks:
-      - events-network
-    healthcheck:
-      test: [ "CMD-SHELL", "curl -f http://localhost:9000/health || exit 1" ]
-      interval: 30s
-      timeout: 10s
-      retries: 5
-      start_period: 10s
-
-  pinot-broker:
-    image: ${PINOT_IMAGE:-apachepinot/pinot:1.2.0}
-    command: "StartBroker -zkAddress pinot-zookeeper:2181"
-    container_name: "pinot-broker"
-    restart: unless-stopped
-    ports:
-      - "8099:8099"
-    environment:
-      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-broker.log"
-    depends_on:
-      pinot-controller:
-        condition: service_healthy
-    networks:
-      - events-network
-    healthcheck:
-      test: [ "CMD-SHELL", "curl -f http://localhost:8099/health || exit 1" ]
-      interval: 30s
-      timeout: 10s
-      retries: 5
-      start_period: 10s
-
-  pinot-server:
-    image: ${PINOT_IMAGE:-apachepinot/pinot:1.2.0}
-    command: "StartServer -zkAddress pinot-zookeeper:2181"
-    container_name: "pinot-app"
-    restart: unless-stopped
-    ports:
-      - "8098:8098"
-    environment:
-      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx16G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-app.log"
-    depends_on:
-      pinot-broker:
-        condition: service_healthy
-    networks:
-      - events-network
-    healthcheck:
-      test: [ "CMD-SHELL", "curl -f http://localhost:8097/health/readiness || exit 1" ]
-      interval: 30s
-      timeout: 10s
-      retries: 5
-      start_period: 10s
-  pinot-up:
-    image: curlimages/curl:latest
-    container_name: pinot-up
-    entrypoint: >
-      /bin/sh -c "
-        echo 'Creating schema...';
-        curl -X POST -H 'Content-Type: application/json' -d @/tmp/schema.json http://pinot-controller:9000/schemas &&
-        echo 'Creating table...';
-        curl -X POST -H 'Content-Type: application/json' -d @/tmp/table_config.json http://pinot-controller:9000/tables"
-    volumes:
-      - ./fs/pinot/event-schema.json:/tmp/schema.json
-      - ./fs/pinot/events-table.json:/tmp/table_config.json
-    networks:
-      - events-network
-    restart: "no"
-    depends_on:
-      pinot-controller:
-        condition: service_healthy
-    environment:
-      JAVA_OPTS: "-Xms1G -Xmx2G"
+#  pinot-controller:
+#    image: ${PINOT_IMAGE:-apachepinot/pinot:1.2.0}
+#    command: "StartController -zkAddress pinot-zookeeper:2181"
+#    container_name: "pinot-controller"
+#    restart: unless-stopped
+#    ports:
+#      - "9000:9000"
+#    environment:
+#      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-controller.log"
+#    depends_on:
+#      pinot-zookeeper:
+#        condition: service_healthy
+#    networks:
+#      - events-network
+#    healthcheck:
+#      test: [ "CMD-SHELL", "curl -f http://localhost:9000/health || exit 1" ]
+#      interval: 30s
+#      timeout: 10s
+#      retries: 5
+#      start_period: 10s
+#
+#  pinot-broker:
+#    image: ${PINOT_IMAGE:-apachepinot/pinot:1.2.0}
+#    command: "StartBroker -zkAddress pinot-zookeeper:2181"
+#    container_name: "pinot-broker"
+#    restart: unless-stopped
+#    ports:
+#      - "8099:8099"
+#    environment:
+#      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-broker.log"
+#    depends_on:
+#      pinot-controller:
+#        condition: service_healthy
+#    networks:
+#      - events-network
+#    healthcheck:
+#      test: [ "CMD-SHELL", "curl -f http://localhost:8099/health || exit 1" ]
+#      interval: 30s
+#      timeout: 10s
+#      retries: 5
+#      start_period: 10s
+#
+#  pinot-server:
+#    image: ${PINOT_IMAGE:-apachepinot/pinot:1.2.0}
+#    command: "StartServer -zkAddress pinot-zookeeper:2181"
+#    container_name: "pinot-app"
+#    restart: unless-stopped
+#    ports:
+#      - "8098:8098"
+#    environment:
+#      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx16G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-app.log"
+#    depends_on:
+#      pinot-broker:
+#        condition: service_healthy
+#    networks:
+#      - events-network
+#    healthcheck:
+#      test: [ "CMD-SHELL", "curl -f http://localhost:8097/health/readiness || exit 1" ]
+#      interval: 30s
+#      timeout: 10s
+#      retries: 5
+#      start_period: 10s
+#  pinot-up:
+#    image: curlimages/curl:latest
+#    container_name: pinot-up
+#    entrypoint: >
+#      /bin/sh -c "
+#        echo 'Creating schema...';
+#        curl -X POST -H 'Content-Type: application/json' -d @/tmp/schema.json http://pinot-controller:9000/schemas &&
+#        echo 'Creating table...';
+#        curl -X POST -H 'Content-Type: application/json' -d @/tmp/table_config.json http://pinot-controller:9000/tables"
+#    volumes:
+#      - ./fs/pinot/event-schema.json:/tmp/schema.json
+#      - ./fs/pinot/events-table.json:/tmp/table_config.json
+#    networks:
+#      - events-network
+#    restart: "no"
+#    depends_on:
+#      pinot-controller:
+#        condition: service_healthy
+#    environment:
+#      JAVA_OPTS: "-Xms1G -Xmx2G"
 
 networks:
   druid:
@@ -294,6 +313,8 @@ networks:
   package-service:
     driver: bridge
   profile-manager:
+    driver: bridge
+  state-service:
     driver: bridge
 
 volumes:
